name: Add PR Approval Label

on:
  pull_request_review:
    types: [ submitted ]
    paths:
      - 'src/helpers/add-pr-approval-label.ts'

jobs:
  test:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./
        with:
          helper: add-pr-approval-label
          login: ${{ github.event.review.user.login }}
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} # must have read:org permission
