name: Add Late Review Label

on:
  pull_request_review:
    types: [submitted]
    paths:
      - 'src/helpers/add-late-review-label.ts'

jobs:
  test:
    if: github.event.review.state == 'blocked'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: ./
        with:
          helper: add-late-review-label
          login: ${{ github.event.review.user.login }}
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} # must have read:org permission
