name: Auto Approve PR

on:
  pull_request:
    branches: [main]
    paths:
      - 'src/helpers/approve-pr.ts'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./
        with:
          helper: approve-pr
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} # must have write:repo permission
