name: Auto Approve PR

on:
  pull_request:
    branches: [ main ]
    types: [ opened ]

jobs:
  test:
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./
        with:
          helper: approve-pr
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} # must have write:repo permission
