name: Approvals Satisfied

on:
  pull_request:
    branches: [main]
    paths:
      - 'src/helpers/approvals-satisfied.ts'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./
        id: approvals-satisfied
        with:
          helper: approvals-satisfied
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - if: steps.approvals-satisfied.outputs.output == 'true'
        run: echo "PR approvals have been satisfied!"
