name: Are Reviewers Requested

on:
  pull_request:
    branches: [main]
    paths:
      - 'src/helpers/are-reviewers-required.ts'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./
        with:
          helper: are-reviewers-required
          teams: '@ExpediaGroup/github-helpers-committers'
