name: Are Reviewers Requested

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/helpers/are-reviewers-requested.ts'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./
        with:
          helper: are-reviewers-requested
