name: Assign PR Reviewer

on:
  pull_request_review:
    types: [ submitted ]
    paths:
      - 'src/helpers/assign-pr-reviewers.ts'

jobs:
  test:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./
        with:
          helper: assign-pr-reviewers
          teams: Repo-Maintainers
          login: ${{ github.event.review.user.login }}
          pull_number: ${{ github.event.pull_request.number }}
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} # must have read:org permission
