name: Check Files for Regex

on:
  pull_request_target:
    branches: [ main ]
    paths:
      - 'src/helpers/check-files-for-regex.ts'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - uses: ./
        with:
          helper: check-files-for-regex
          namingConvention: 'src/main/resources/messages_[a-z]{2}_[A-Z]{2}.properties'
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
