name: Close Pr

on:
  pull_request:
    branches: [ main ]
    types: [ opened, reopened ]
    paths:
      - 'src/helpers/close-pr.ts'

permissions: write-all

jobs:
  test:
    if: contains(github.event.pull_request.labels.*.name, 'CLOSE ME')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./
        with:
          helper: close-pr
          body: Closing this PR for testing purposes!
