name: Create Project Card

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/helpers/create-project-card.ts'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./
        with:
          helper: create-project-card
          project_name: 'test project'
          note: 'This PR is adding this note cause it needs it. You should not place notes too frequent, but it is what it is.'
          project_destination_column_name: 'test column 1'
          pull_number: ${{ github.event.pull_request.number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
