name: Create Batched Commit Message

on:
  push:
    branches: [batched-commits]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./
        with:
          helper: create-batched-commit-message
