name: Delete Stale Branches

on:
  pull_request:
    branches: [main]
    paths:
      - 'src/helpers/delete-stale-branches.ts'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./
        with:
          helper: delete-stale-branches
