name: Deployments

on:
  pull_request_target:
    branches: [main]
    paths:
      - 'src/helpers/delete-deployment.ts'
      - 'src/helpers/initiate-deployment.ts'
      - 'src/helpers/set-deployment-status.ts'

jobs:
  initiate-deployment:
    name: Initiate Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - uses: ./
        with:
          helper: initiate-deployment
          sha: ${{ github.event.pull_request.head.sha }}
          environment: test
          description: PR#${{ github.event.pull_request.number }} has been merged; pipeline in progress...
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

  set-deployment-status:
    name: Set Deployment Status
    needs: [initiate-deployment]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - uses: ./
        with:
          helper: set-deployment-status
          sha: ${{ github.event.pull_request.head.sha }}
          environment: test
          state: success
          description: Deployment succeeded.
          target_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

  delete-deployment:
    name: Delete Deployment
    needs: [initiate-deployment, set-deployment-status]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - uses: ./
        with:
          helper: delete-deployment
          sha: ${{ github.event.pull_request.head.sha }}
          environment: test
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
