name: Filter Paths

on:
  pull_request:
    branches: [main]
    paths:
      - 'src/helpers/filter-paths.ts'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./
        id: paths
        with:
          helper: filter-paths
          paths: |
            src
            package.json
            yarn.lock

      - if: steps.paths.outputs.output == 'true'
        run: echo "One of those file paths changed!"
