name: Filter Paths

on:
  pull_request_target:
    branches: [ main ]
    paths:
      - 'src/helpers/filter-paths.ts'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - uses: ./
        id: paths
        with:
          helper: filter-paths
          paths: |
            src
            package.json
            yarn.lock
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - if: steps.paths.outputs.output == 'true'
        run: echo "One of those file paths changed!"
