name: Get Labels

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/helpers/get-labels.ts'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - uses: ./
        with:
          helper: get-labels
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
