name: Get Changed Files

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/helpers/get-changed-files.ts'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./
        id: changed
        with:
          helper: get-changed-files
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - run: echo "Changed files are ${{ steps.changed.outputs.output }}"
