name: Get Changed Files

on:
  pull_request_target:
    branches: [main]
    paths:
      - 'src/helpers/get-changed-files.ts'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - uses: ./
        id: changed
        with:
          helper: get-changed-files
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - run: echo "Changed files are ${{ steps.changed.outputs.output }}"
