name: Initiate Deployment

on:
  pull_request_target:
    branches: [ main ]
    paths:
      - 'src/helpers/initiate-deployment.ts'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - uses: ./
        with:
          helper: initiate-deployment
          sha: HEAD
          environment: production
          description: PR#${{ github.event.pull_request.number }} has been merged; pipeline in progress...
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
