name: Manage Merge Queue

on:
  pull_request_target:
    branches: [ main ]
    types: [ synchronize, labeled, unlabeled, closed ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - uses: ./
        with:
          helper: manage-merge-queue
          sha: ${{ github.event.pull_request.head.sha }}
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} # must have repo:write permission
