name: Manage Merge Queue

on:
  pull_request:
    branches: [ main ]
    types: [ labeled, unlabeled, closed ]

jobs:
  test:
    if: |
      github.event.action == 'closed' ||
      github.event.label.name == 'READY FOR MERGE' ||
      github.event.label.name == 'JUMP THE QUEUE'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./
        with:
          helper: manage-merge-queue
