name: Manage Merge Queue

on:
  pull_request:
    branches: [ main ]
    types: [ synchronize, labeled, unlabeled, closed ]

jobs:
  test:
    if: github.event.action != 'closed' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./
        with:
          helper: manage-merge-queue
          sha: ${{ github.event.pull_request.head.sha }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
