name: Move Project Card

on:
  pull_request_target:
    branches: [ main ]
    paths:
      - 'src/helpers/move-project-card.ts'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - uses: ./
        with:
          helper: move-project-card
          project_name: Test Project
          project_origin_column_name: Test Column 1
          project_destination_column_name: Test Column 2
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
