name: Move Project Card

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/helpers/move-project-card.ts'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./
        with:
          helper: move-project-card
          project_name: 'PR-Review-queue'
          project_destination_column_name: 'Ready for Core Review QUEUE'
          project_origin_column_name: 'Waiting for Peer Approval'
          pull_number: ${{ github.event.pull_request.number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
