name: Prepare Queued PR For Merge

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/helpers/prepare-queued-pr-for-merge.ts'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./
        with:
          helper: prepare-queued-pr-for-merge
