name: Publish

on:
  release:
    types: [ edited, published ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Major Version
        run: |
          MAJOR_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3 | cut -d "." -f1)
          echo "New version: ${MAJOR_VERSION}"
          git tag ${MAJOR_VERSION}
          git push --tags -f
