name: Rebase Pr

#on:
#  workflow_dispatch:
#    inputs:
#      pull_number:
#        description: The pull request number
#        required: true
#        type: string

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - uses: ./
        with:
          helper: rebase-pr
          pull_number: 210
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
