name: Remove Label

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/helpers/remove-label.ts'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./
        with:
          helper: remove-label
          label: Test Label
          github_token: ${{ secrets.GITHUB_TOKEN }}
