name: Remove Pr From Merge Queue

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/helpers/remove-pr-from-merge-queue.ts'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./
        with:
          helper: remove-pr-from-merge-queue
          seconds: 3600
