name: Reopen Pr

on:
  pull_request:
    branches: [main]
    paths:
      - 'src/helpers/reopen-pr.ts'

jobs:
  test:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v5

    - uses: ./
      with:
        helper: reopen-pr
