name: Rerun PR Checks

on:
  pull_request:
    types: [ labeled ]

jobs:
  test:
    if: ${{ github.event.label.name == 'RE-RUN PR CHECKS' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./
        with:
          helper: rerun-pr-checks

      - uses: ./
        with:
          helper: remove-label
          label: RE-RUN PR CHECKS
