name: Set Deployment Status

on:
  pull_request_target:
    branches: [ main ]
    paths:
      - 'src/helpers/set-deployment-status.ts'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - uses: ./
        with:
          helper: set-deployment-status
          sha: ${{ github.event.pull_request.head.sha }}
          environment: pr-123
          state: in_progress
          description: Deployment in progress.
          target_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
