name: Set Commit Status

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./
        with:
          helper: set-commit-status
          sha: ${{ github.event.pull_request.head.sha }}
          context: Commit Status Test
          state: success
          description: set-commit-status is working!
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
