name: Set Deployment Status

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/helpers/set-deployment-status.ts'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./
        with:
          helper: set-deployment-status
          sha: ${{ github.event.pull_request.head.sha }}
          environment: pr-123
          state: in_progress
          description: Deployment in progress.
          target_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
