name: Update Check Result

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/helpers/update-check-result.ts'

jobs:
  test:
    name: Update Check Result
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./
        with:
          helper: update-check-result
          context: Update Check Result
          sha: ${{ github.event.pull_request.head.sha }}
          state: success
