name: Update Merge Queue

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./
        with:
          helper: manage-merge-queue
          github_token: ${{ secrets.GITHUB_TOKEN }}
